
class SystemConstants:
    """
    👑 TRỤC TỌA ĐỘ HẰNG SỐ CHUNG TOÀN HỆ THỐNG FINTECH MONOLITH
    🎯 Mục đích:
       - Tập trung toàn bộ mã định danh lỗi (Error Codes), thông báo (Messages), nhãn (Labels).
       - Khớp 100% với key trong các file từ điển i18n (errors.json, messages.json, labels.json).
       - Tránh magic strings, hỗ trợ IDE auto-complete và type checking.
    """

    # =========================================================================
    # ✅ 0. MÃ THÀNH CÔNG (SUCCESS CODES)
    # =========================================================================
    SYSTEM_SUCCESS = "SUCCESS_200"
    SUCCESS = "SUCCESS"
    AI_ANALYSIS_SUCCESS = "AI_ANALYSIS_SUCCESS"
    PIGGY_CONFIG_UPDATE_SUCCESS = "PIGGY_CONFIG_UPDATE_SUCCESS"
    PIGGY_FETCH_SUCCESS = "PIGGY_FETCH_SUCCESS"

    # =========================================================================
    # ❌ 1. PHÂN HỆ LỖI HỆ THỐNG NỘI BỘ (SYSTEM ERRORS - 5xx)
    # =========================================================================
    INTERNAL_SERVER_ERROR = "500"
    DATABASE_CONNECTION_FAILED = "501"
    REDIS_UNAVAILABLE = "502"
    KAFKA_UNAVAILABLE = "503"
    SERVICE_TEMPORARILY_UNAVAILABLE = "504"
    TOO_MANY_REQUESTS = "429"
    GLOBAL_INTERNAL_SERVER_ERROR = "505"
    GLOBAL_INVALID_REQUEST_PAYLOAD = "405"
    GLOBAL_TOO_MANY_REQUESTS = "GLOBAL_TOO_MANY_REQUESTS"

    # Crash / Exception Error Codes
    REGISTRATION_INTERNAL_CRASH = "REGISTRATION_INTERNAL_CRASH"
    LOGIN_INTERNAL_CRASH = "LOGIN_INTERNAL_CRASH"
    TOKEN_REFRESH_CRASH = "TOKEN_REFRESH_CRASH"
    LOGOUT_INTERNAL_CRASH = "LOGOUT_INTERNAL_CRASH"
    ACTIVATE_LINK_CRASH = "ACTIVATE_LINK_CRASH"
    OTP_VERIFICATION_CRASH = "OTP_VERIFICATION_CRASH"
    REPORT_INTERNAL_CRASH = "REPORT_INTERNAL_CRASH"
    REGISTRATION_PROCESSOR_CRASH = "REGISTRATION_PROCESSOR_CRASH"
    LOGIN_PROCESSOR_CRASH = "LOGIN_PROCESSOR_CRASH"
    USER_CREATION_DATABASE_FAILED = "USER_CREATION_DATABASE_FAILED"
    ACTIVATION_TX_COMMIT_FAILED = "ACTIVATION_TX_COMMIT_FAILED"
    NOTIFICATION_QUEUE_FAILED = "NOTIFICATION_QUEUE_FAILED"
    CORE_TRANSACTION_EXECUTION_FAILED = "CORE_TRANSACTION_EXECUTION_FAILED"

    # =========================================================================
    # ❌ 2. PHÂN HỆ LỖI XÁC THỰC & PHÂN QUYỀN (AUTH & SECURITY)
    # =========================================================================
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"
    ACCESS_DENIED_MODULE_RESTRICTED = "AUTH-4001"
    USER_ACCOUNT_BLOCKED = "USER_ACCOUNT_BLOCKED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_ACTIVE = "USER_ALREADY_ACTIVE"
    ACCOUNT_PENDING_ACTIVATION = "AUTH-3004"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_NULL = "TOKEN_NULL"
    INVALID_TOKEN_FORMAT = "INVALID_TOKEN_FORMAT"
    FORBIDDEN_REGISTRATION = "FORBIDDEN_REGISTRATION"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # OTP & Link Token Error Codes
    LINK_TOKEN_EXPIRED = "LINK_TOKEN_EXPIRED"
    INVALID_OR_USED_LINK_TOKEN = "INVALID_OR_USED_LINK_TOKEN"
    INVALID_OTP_CODE = "INVALID_OTP_CODE"
    INVALID_OTP_FORMAT = "INVALID_OTP_FORMAT"
    INVALID_OR_EXPIRED_OTP = "INVALID_OR_EXPIRED_OTP"
    OTP_NOT_FOUND = "OTP_NOT_FOUND"
    OTP_TIMEOUT_EXPIRED = "OTP_TIMEOUT_EXPIRED"
    OTP_BRUTE_FORCE_LOCKED = "OTP_BRUTE_FORCE_LOCKED"
    OTP_GENERATION_DATABASE_FAILED = "OTP_GENERATION_DATABASE_FAILED"
    INVALID_VERIFY_OTP_PAYLOAD = "INVALID_VERIFY_OTP_PAYLOAD"

    # Backward compatibility error codes
    AUTH_INVALID_CREDENTIALS = "101"
    AUTH_ACCESS_TOKEN_EXPIRED = "102"
    AUTH_ACCOUNT_LOCKED = "103"
    AUTH_USERNAME_EXISTS = "104"
    AUTHENTICATION_TOKEN_EXPIRED = "AUTH-3005"
    MISSING_AUTHENTICATION_TOKEN = "AUTH-3006"
    INVALID_AUTHENTICATION_TOKEN = "AUTH-3007"

    # =========================================================================
    # ❌ 3. PHÂN HỆ LỖI VALIDATION & INPUT CHECKING (4xx)
    # =========================================================================
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_ERROR_400 = "VALIDATION_ERROR_400"
    INVALID_REQUEST_PAYLOAD = "400"
    IP_NOT_ALLOWED = "403"
    UNAUTHORIZED_ACCESS = "402"

    # Validation trường dữ liệu
    MISSING_USERNAME = "MISSING_USERNAME"
    MISSING_EMAIL = "MISSING_EMAIL"
    MISSING_PHONE = "MISSING_PHONE"
    MISSING_PASSWORD = "MISSING_PASSWORD"
    MISSING_CONFIRM_PASSWORD = "MISSING_CONFIRM_PASSWORD"
    MISSING_FULL_NAME = "MISSING_FULL_NAME"
    MISSING_DATE_OF_BIRTH = "MISSING_DATE_OF_BIRTH"
    MISSING_GENDER = "MISSING_GENDER"

    INVALID_USERNAME_LENGTH = "INVALID_USERNAME_LENGTH"
    USERNAME_HAS_WHITESPACE = "USERNAME_HAS_WHITESPACE"
    INVALID_USERNAME_CHARACTERS = "INVALID_USERNAME_CHARACTERS"
    FORBIDDEN_USERNAME = "FORBIDDEN_USERNAME"

    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PHONE_FORMAT = "INVALID_PHONE_FORMAT"
    INVALID_PASSWORD_LENGTH = "INVALID_PASSWORD_LENGTH"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    INVALID_FULL_NAME_LENGTH = "INVALID_FULL_NAME_LENGTH"
    XSS_DETECTED_IN_NAME = "XSS_DETECTED_IN_NAME"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
    USER_UNDER_AGE = "USER_UNDER_AGE"
    INVALID_GENDER_ENUM = "INVALID_GENDER_ENUM"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    INVALID_REGISTER_DATA = "108"

    # =========================================================================
    # ❌ 4. PHÂN HỆ VÍ & GIAO DỊCH (WALLET & TRANSACTIONS)
    # =========================================================================
    WALLET_NOT_FOUND = "WALLET_NOT_FOUND"
    WALLET_ALREADY_EXISTS = "WALLET_400_003"
    WALLET_ACCESS_DENIED = "WALLET_403_001"
    WALLET_FORBIDDEN_ACCESS = "WALLET_FORBIDDEN_ACCESS"
    WALLET_INVALID_STATUS = "WALLET_422_001"
    WALLET_INACTIVE = "WALLET_INACTIVE"
    WALLET_DELETED = "WALLET_DELETED"
    MISSING_WALLET_CODE = "MISSING_WALLET_CODE"
    MISSING_WALLET_NAME = "MISSING_WALLET_NAME"
    INVALID_WALLET_CODE_LENGTH = "INVALID_WALLET_CODE_LENGTH"
    INVALID_WALLET_NAME_LENGTH = "INVALID_WALLET_NAME_LENGTH"
    INVALID_WALLET_ACCOUNT_DIGITS = "INVALID_WALLET_ACCOUNT_DIGITS"

    # Topup & Transaction Error Codes
    INVALID_TOPUP_AMOUNT = "TRANSACTION_400_001"
    INVALID_AMOUNT_POSITIVE = "INVALID_AMOUNT_POSITIVE"
    INVALID_AMOUNT_MAX_LIMIT = "INVALID_AMOUNT_MAX_LIMIT"
    INVALID_AMOUNT_DECIMALS = "INVALID_AMOUNT_DECIMALS"
    DAILY_TOPUP_LIMIT_EXCEEDED = "DAILY_TOPUP_LIMIT_EXCEEDED"
    MONTHLY_TOPUP_LIMIT_EXCEEDED = "MONTHLY_TOPUP_LIMIT_EXCEEDED"
    DUPLICATE_TRANSACTION_DETECTED = "DUPLICATE_TRANSACTION_DETECTED"
    DUPLICATE_IDEMPOTENCY_TRANSACTION_REJECTED = "DUPLICATE_IDEMPOTENCY_TRANSACTION_REJECTED"
    MISSING_REQUIRED_IDEMPOTENCY_KEY = "MISSING_REQUIRED_IDEMPOTENCY_KEY"
    TRANSACTION_IN_PROGRESS_LOCK = "TRANSACTION_IN_PROGRESS_LOCK"
    TRANSACTION_COMMIT_FAILED = "TRANSACTION_COMMIT_FAILED"
    IDEMPOTENCY_CONFLICT = "TRANSACTION_409_001"
    TOPUP_INTERNAL_CRASH = "TOPUP_INTERNAL_CRASH"
    UPDATE_FAILED = "UPDATE_FAILED"

    # Budget & Financial Goals Error Codes
    MISSING_BUDGET_NAME = "MISSING_BUDGET_NAME"
    INVALID_BUDGET_AMOUNT = "INVALID_BUDGET_AMOUNT"
    BUDGET_CATEGORY_NOT_FOUND = "BUDGET_CATEGORY_NOT_FOUND"

    # Bank Account & Financial Ledger
    BANK_ACCOUNT_NOT_FOUND = "BANK_ACCOUNT_NOT_FOUND"
    BANK_ACCOUNT_NAME_MISMATCH = "BANK_ACCOUNT_NAME_MISMATCH"
    BANK_ACCOUNT_INACTIVE = "BANK_ACCOUNT_INACTIVE"
    INVALID_ACCOUNT_NUMBER_FORMAT = "INVALID_ACCOUNT_NUMBER_FORMAT"
    INVALID_BANK_NAME_FORMAT = "INVALID_BANK_NAME_FORMAT"
    INVALID_ACCOUNT_NAME_FORMAT = "INVALID_ACCOUNT_NAME_FORMAT"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    INVALID_CURRENCY_ENUM = "INVALID_CURRENCY_ENUM"
    BANK_INSUFFICIENT_BALANCE = "BANK_INSUFFICIENT_BALANCE"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    BALANCE_INCONSISTENCY_DETECTED = "BALANCE_INCONSISTENCY_DETECTED"
    INSUFFICIENT_BALANCE = "TRANSFER_400_002"
    FINANCIAL_LEDGER_INSUFFICIENT_BALANCE = "FINANCIAL_LEDGER_INSUFFICIENT_BALANCE"
    INVALID_FINANCIAL_LEDGER_AMOUNT = "INVALID_FINANCIAL_LEDGER_AMOUNT"

    # =========================================================================
    # 🎉 5. PHÂN HỆ THÔNG BÁO THÀNH CÔNG (SUCCESS MESSAGES)
    # =========================================================================
    USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
    USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
    ACCOUNT_ACTIVATION_SUCCESS = "ACCOUNT_ACTIVATION_SUCCESS"
    TOKEN_VALID_OTP_GENERATED = "TOKEN_VALID_OTP_GENERATED"
    TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS"
    AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
    AUTH_OTP_SENT_SUCCESS = "AUTH_OTP_SENT_SUCCESS"
    AUTH_PASSWORD_RESET_SUCCESS = "AUTH_PASSWORD_RESET_SUCCESS"
    AUTH_PASSWORD_CHANGED_SUCCESS = "AUTH_PASSWORD_CHANGED_SUCCESS"

    USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS"
    USER_AVATAR_UPDATE_SUCCESS = "USER_AVATAR_UPDATE_SUCCESS"
    USER_STATUS_UPDATE_SUCCESS = "USER_STATUS_UPDATE_SUCCESS"
    USER_ROLE_ASSIGN_SUCCESS = "USER_ROLE_ASSIGN_SUCCESS"

    WALLET_CREATE_SUCCESS = "WALLET_CREATE_SUCCESS"
    WALLET_FETCH_SUCCESS = "WALLET_FETCH_SUCCESS"
    WALLET_UPDATE_SUCCESS = "WALLET_UPDATE_SUCCESS"
    WALLET_DELETE_SUCCESS = "WALLET_DELETE_SUCCESS"
    WALLET_FREEZE_SUCCESS = "WALLET_FREEZE_SUCCESS"
    WALLET_UNFREEZE_SUCCESS = "WALLET_UNFREEZE_SUCCESS"
    WALLET_SET_DEFAULT_SUCCESS = "WALLET_SET_DEFAULT_SUCCESS"

    WALLET_TOPUP_SUCCESS = "WALLET_TOPUP_SUCCESS"
    TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS"
    TRANSACTION_CANCEL_SUCCESS = "TRANSACTION_CANCEL_SUCCESS"
    TRANSACTION_EXPORT_SUCCESS = "TRANSACTION_EXPORT_SUCCESS"

    TRANSFER_EXECUTE_SUCCESS = "TRANSFER_EXECUTE_SUCCESS"
    TRANSFER_REVERSE_SUCCESS = "TRANSFER_REVERSE_SUCCESS"

    BUDGET_CREATE_SUCCESS = "BUDGET_CREATE_SUCCESS"
    BUDGET_UPDATE_SUCCESS = "BUDGET_UPDATE_SUCCESS"
    BUDGET_DELETE_SUCCESS = "BUDGET_DELETE_SUCCESS"
    FINANCIAL_GOAL_CREATE_SUCCESS = "FINANCIAL_GOAL_CREATE_SUCCESS"
    FINANCIAL_GOAL_UPDATE_SUCCESS = "FINANCIAL_GOAL_UPDATE_SUCCESS"

    LEDGER_JOURNAL_POSTED_SUCCESS = "LEDGER_JOURNAL_POSTED_SUCCESS"
    LEDGER_RECONCILE_SUCCESS = "LEDGER_RECONCILE_SUCCESS"
    LEDGER_PERIOD_CLOSED_SUCCESS = "LEDGER_PERIOD_CLOSED_SUCCESS"

    PIGGY_LINK_SUCCESS = "PIGGY_LINK_SUCCESS"
    PIGGY_UNLINK_SUCCESS = "PIGGY_UNLINK_SUCCESS"
    PIGGY_SYNC_SUCCESS = "PIGGY_SYNC_SUCCESS"
    PIGGY_CONFIG_UPDATE_SUCCESS = "PIGGY_CONFIG_UPDATE_SUCCESS"

    OCR_SCAN_SUCCESS = "OCR_SCAN_SUCCESS"
    AI_ANALYSIS_SUCCESS = "AI_ANALYSIS_SUCCESS"
    AI_PREDICTION_SUCCESS = "AI_PREDICTION_SUCCESS"

    NOTIFICATION_MARK_READ_SUCCESS = "NOTIFICATION_MARK_READ_SUCCESS"
    NOTIFICATION_CLEAR_ALL_SUCCESS = "NOTIFICATION_CLEAR_ALL_SUCCESS"
    PUSH_DEVICE_REGISTER_SUCCESS = "PUSH_DEVICE_REGISTER_SUCCESS"

    FETCH_REPORT_SUCCESS = "FETCH_REPORT_SUCCESS"
    REPORT_EXPORT_SUCCESS = "REPORT_EXPORT_SUCCESS"

    USER_PROFILE_FETCH_SUCCESS = "USER_PROFILE_FETCH_SUCCESS"
    CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS"
    CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS"
    TRANSACTION_FETCH_SUCCESS = "TRANSACTION_FETCH_SUCCESS"
    TRANSFER_FETCH_SUCCESS = "TRANSFER_FETCH_SUCCESS"
    BUDGET_FETCH_SUCCESS = "BUDGET_FETCH_SUCCESS"
    PIGGY_FETCH_SUCCESS = "PIGGY_FETCH_SUCCESS"
    AI_SCORE_CALCULATE_SUCCESS = "AI_SCORE_CALCULATE_SUCCESS"
    AI_RECOMMENDATION_SUCCESS = "AI_RECOMMENDATION_SUCCESS"
    MISSING_CATEGORY_NAME = "MISSING_CATEGORY_NAME"
    INVALID_CATEGORY_TYPE = "INVALID_CATEGORY_TYPE"
    INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
    INSUFFICIENT_WALLET_BALANCE = "INSUFFICIENT_WALLET_BALANCE"
    SAME_SOURCE_DESTINATION_WALLET = "SAME_SOURCE_DESTINATION_WALLET"
    SOURCE_WALLET_NOT_FOUND = "SOURCE_WALLET_NOT_FOUND"
    DESTINATION_WALLET_NOT_FOUND = "DESTINATION_WALLET_NOT_FOUND"
    BUDGET_NOT_FOUND = "BUDGET_NOT_FOUND"
    MISSING_WALLET_ID = "MISSING_WALLET_ID"
    MISSING_CATEGORY_ID = "MISSING_CATEGORY_ID"
    MISSING_AMOUNT = "MISSING_AMOUNT"
    MISSING_SOURCE_WALLET_ID = "MISSING_SOURCE_WALLET_ID"
    MISSING_DESTINATION_WALLET_ID = "MISSING_DESTINATION_WALLET_ID"
    MISSING_DEVICE_CODE = "MISSING_DEVICE_CODE"
    MISSING_IMAGE_DATA = "MISSING_IMAGE_DATA"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    TRANSFER_NOT_FOUND = "TRANSFER_NOT_FOUND"
    OLD_PASSWORD_INCORRECT = "OLD_PASSWORD_INCORRECT"
    NEW_PASSWORD_SAME_AS_OLD = "NEW_PASSWORD_SAME_AS_OLD"

    # Backward compatibility success codes
    AUTH_REGISTER_SUCCESS = "001"
    AUTH_LOGIN_SUCCESS = "002"

    # =========================================================================
    # 🏷️ 6. PHÂN HỆ NHÃN HIỂN THỊ, LOẠI THÔNG ĐIỆP & TRẠNG THÁI (LABELS & ENUMS)
    # =========================================================================
    MSG_TYPE_ERROR = "ERROR"
    MSG_TYPE_MESSAGE = "MESSAGE"
    MSG_TYPE_LABEL = "LABEL"

    LABEL_USER_ID = "901"
    LABEL_USERNAME = "902"
    LABEL_EMAIL = "903"
    REGISTER_VERIFY_MAIL_BODY = "REGISTER_VERIFY_MAIL_BODY"
    REGISTER_VERIFY_MAIL_SUBJECT = "REGISTER_VERIFY_MAIL_SUBJECT"

    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    BLOCKED = "BLOCKED"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"

    # =========================================================================
    # 👑 7. MA TRẬN MÃ MODULE & MÃ QUYỀN PHÂN HỆ
    # =========================================================================
    MODULE_AUTH_MGMT = "AUTH_MGMT"
    MODULE_USER_MGMT = "USER_MGMT"
    MODULE_WALLET_MGMT = "WALLET_MGMT"
    MODULE_TRANSACTION_MGMT = "TRANSACTION_MGMT"
    MODULE_TRANSFER_MGMT = "TRANSFER_MGMT"
    MODULE_BUDGET_MGMT = "BUDGET_MGMT"
    MODULE_LEDGER_MGMT = "LEDGER_MGMT"
    MODULE_IOT_PIGGY_MGMT = "IOT_PIGGY_MGMT"
    MODULE_AI_OCR_MGMT = "AI_OCR_MGMT"
    MODULE_REPORT_MGMT = "REPORT_MGMT"
    MODULE_AUDIT_MGMT = "AUDIT_MGMT"

    # Mã quyền chi tiết (Permissions)
    PERMISSION_WALLET_CREATE = "WALLET_CREATE"
    PERMISSION_WALLET_DETAIL = "WALLET_DETAIL"
    PERMISSION_WALLET_LIST = "WALLET_LIST"
    PERMISSION_WALLET_UPDATE = "WALLET_UPDATE"
    PERMISSION_WALLET_DELETE = "WALLET_DELETE"
    PERMISSION_WALLET_TOPUP = "WALLET_TOPUP"
    PERMISSION_USER_VIEW = "USER_VIEW"
    PERMISSION_USER_UPDATE = "USER_UPDATE"
    PERMISSION_REPORT_VIEW = "REPORT_VIEW"
    PERMISSION_REPORT_EXPORT = "REPORT_EXPORT"
    PERMISSION_BUDGET_CREATE = "BUDGET_CREATE"
    PERMISSION_BUDGET_VIEW = "BUDGET_VIEW"
    PERMISSION_TRANSFER_EXECUTE = "TRANSFER_EXECUTE"
    PERMISSION_LEDGER_VIEW = "LEDGER_VIEW"
    PERMISSION_PIGGY_SYNC = "PIGGY_SYNC"